✨ Dockerfile 작성
telos-projects/fish-25 pull request #27
Opened 2022-04-18 12:57 UTC by Junnyjun

- [x] CI 컨테이너링 작업

2022-04-18 13:00 UTC, shirohoo requested changes
샵(#) 두개 다음에는 세개로 작성 바랍니다.

2022-04-18 13:01 UTC, Junnyjun reviewed
했습니다

2022-04-18 13:09 UTC, shirohoo requested changes

2022-04-18 13:09 UTC, shirohoo commented on infra/docker/server/Dockerfile
> +"/opt/app/fish25.jar"]
jar 커맨드에 GC로그 명령어 추가 바랍니다.

```
-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:GCLogFileSize=50m -XX:NumberOfGCLogFiles=5 -Xloggc:/home/tomcat/gc/addition-gc.log
```

- 예시

```
java -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:GCLogFileSize=50m -XX:NumberOfGCLogFiles=5 -Xloggc:/home/gc/fish25-gc.log -jar -Dspring.profiles.active=${ACTIVE_PROFILE}" -Dserver.port=${INTERNAL_PORT}" /opt/app/fish25.jar
```

2022-04-19 04:38 UTC, Junnyjun commented on infra/docker/server/Dockerfile
> +"/opt/app/fish25.jar"]
넵

2022-04-19 14:21 UTC, closed without merging